global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
 # — “first.rules”
 # — “second.rules”
scrape_configs:
  - job_name: noteit
    static_configs: 10s
      - targets:
      - localhost: 8000